name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - if: matrix.os == 'ubuntu-latest'
        name: Install libxrandr-dev
        run: |
          sudo apt-get update
          sudo apt-get install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

      - name: Set up CMake
        run: make init

      - name: Build
        run: make build all

      - name: Test
        run: make test
