name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Debug, Release]
    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE: ${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - if: matrix.os == 'ubuntu-latest'
        name: Install libxrandr-dev
        run: |
          sudo apt-get update
          sudo apt-get install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

      - name: Set up CMake
        run: make init

      - name: Configure
        run: make configure

      - name: Build Components
        run: make build remus__components

      - name: Build Remus
        run: make build remus

      - name: Build Tests
        run: make build remus__tests

      - name: Test
        run: make test
